### ISSUE TITLE
thermocalc style output file

### ISSUE THREAD

**Issue by kellertobs** [ComputationalThermodynamics/MAGEMin#36]
It would be helpful to add the following information to the thermocalc output file:
- a block with same format as Oxide compositions [mol%] but with weight fractions of stable phases and system.
- add units to all quantities in the block Stable mineral assemblage
These additions would be helpful with creating a Matlab script that provides MELTS-style way to interrogate the equilibrium solver

**Comment by NicolasRiel** [comment]
Hi Tobias,

The original goal of this output was to benchmark MAGEMin against THERMOCALC and it received little attention since then.
Yes I am updating this output accordingly, thanks. I will also make the output parallel. 

For a Matlab wrapper, do you think there is a way for Matlab to retrieve a C structure directly?

**Comment by NicolasRiel** [comment]
This has been added to the development branch and will be pushed to MAGEMin repo soon
