### ISSUE TITLE
A new issue when I use "EquilibriumPath" of new version(1.3.0)

### ISSUE THREAD

**Issue by CHNxzr** [ComputationalThermodynamics/MAGEMin#53]
I have deleted the old version and installed the latest one,  however, a new issue was encountered when I tried to use "EquilibriumPath", while all the parameters kept default. 
![mistake_3 15](https://user-images.githubusercontent.com/114136385/225308639-b367b76e-ec3f-4882-b184-8c3b3edc1503.png)

**Comment by NicolasRiel** [comment]
Ah it's likely that I broke the EquilibriumPath routine when adding this option, it is also likely broken for the database choice too.
I think that as a temporary fix, you can change line 13 to:

solver = 1; (this is default solver)

and line 14:

db = 2; (for igneous)
or
db = 1; (for metapelite)

Could you have a look to what I broke @kellertobs ?

Nicolas

**Comment by kellertobs** [comment]
Yes I just noticed that as well yesterday. The fix is to add new default values to the Computation struct in EquilibriumPath. I haven't yet built in an option to select the metapelite database in the EquilibriumPath script, so for now it's default to igneous.

@NicolasRiel, I'm currently having trouble accessing the MAGEMin_dev repo. Can I send you the fixed script to merge into the dev branch and add to the next release?

**Comment by NicolasRiel** [comment]
Yes sure, I will push it directly to the public version, no need for a new release.

**Comment by NicolasRiel** [comment]
I just pushed the EquilibriumPath_MAGEMin fix from Tobias on the master branch.

This should fix the problem, if not you can re-open the issue!

Nicolas
