### ISSUE TITLE
low fraction of oxygen appear on the phase diagram

### ISSUE THREAD

**Issue by eazzzon** [ComputationalThermodynamics/MAGEMin#56]
Oxygen appear on the phase diagram sometimes even though the fraction is extremely low (see pic below), is there a way to remove oxygen phase or maybe exclude the phase when fraction is < 0.001 ?

<img width="965" alt="image" src="https://user-images.githubusercontent.com/34231327/228532075-8a3ea9a2-5b3f-437f-95f8-bfc2d6da0ca3.png">

**Comment by NicolasRiel** [comment]
Because sometimes users prescribes way too much O, I was taking into account the O2 pure-phase in the list of the potential phases. The idea was to give a hint that the prescribed O-content is too large but I did not expect O2 to have a lower Gibbs than liquid, even outside the calibration range. I will remove it from the pure phase list. 

I cannot push the update now, but if you want to have an updated local version you can modify 

**line 281 of src/initialize.h to:**

`	char    PP[13][20];`

**and line 310 of src/initialize.h to:**

`	{"q"	,"crst"	,"trd"	,"coe"	,"stv"	,"ky"	,"sill"	,"and"	,"ru"	,"sph"	,"wo"	,"pswo"	,"ne"		},`

Then recompile 

`make clean; make all;`

That should solve your problem

Cheers

**Comment by eazzzon** [comment]
> Because sometimes users prescribes way too much O, I was taking into account the O2 pure-phase in the list of the potential phases. The idea was to give a hint that the prescribed O-content is too large but I did not expect O2 to have a lower Gibbs than liquid, even outside the calibration range. I will remove it from the pure phase list.
> 
> I cannot push the update now, but if you want to have an updated local version you can modify
> 
> **line 281 of src/initialize.h to:**
> 
> ` char PP[13][20];`
> 
> **and line 310 of src/initialize.h to:**
> 
> ` {"q" ,"crst" ,"trd" ,"coe" ,"stv" ,"ky" ,"sill" ,"and" ,"ru" ,"sph" ,"wo" ,"pswo" ,"ne" },`
> 
> Then recompile
> 
> `make clean; make all;`
> 
> That should solve your problem
> 
> Cheers

i will wait for the next version then, maybe there could be a tab to choose which phases to saturate or suppress?
