### ISSUE TITLE
wt% input instead of mole fraction for oxides

### ISSUE THREAD

**Issue by wenrongcao** [ComputationalThermodynamics/MAGEMin#84]
Hi, I am wondering if the code (in the web browser) has an option to input oxides using wt% instead of mol_fraction. I think the MATLAB version has the wt% input choice. It will be more convenient if wt% can be used in the web browser version. Thanks for developing the easy-to-use app!

**Comment by NicolasRiel** [comment]
Hi, sure you can input wt%.  
Check here:
https://github.com/ComputationalThermodynamics/MAGEMinApp.jl
You have an example at the end on how to provide an input file and how to set wt% instead of mol%.

Note however that once the bulk loaded they are converted to mol% and displayed as such.

The App is designed in a way that the users need to prepare an input file with the bulk-rock composition they want to use, together with the system unit (mol, wt) and the database (mp, mb, ig, um).

In the MAGEMinApp directory you can also find an example of working input bulk file:

https://github.com/ComputationalThermodynamics/MAGEMinApp.jl/blob/main/examples/bulk-rock_ref.dat

Hope this helps,

Nicolas

**Comment by wenrongcao** [comment]
Great, thanks for the info!
